# Generated by Django 5.2.7 on 2025-11-03 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('position_z', models.FloatField(default=0.0)),
                ('rotation_x', models.FloatField(default=0.0)),
                ('rotation_y', models.FloatField(default=0.0)),
                ('rotation_z', models.FloatField(default=0.0)),
                ('rotation_w', models.FloatField(default=1.0, help_text='Quaternion w component')),
                ('scale_x', models.FloatField(default=1.0)),
                ('scale_y', models.FloatField(default=1.0)),
                ('scale_z', models.FloatField(default=1.0)),
                ('attached_at_point', models.CharField(blank=True, help_text='Connection point identifier where this is attached', max_length=100)),
                ('custom_name', models.CharField(blank=True, help_text='Custom name for this instance', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0, help_text='Order in assembly')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_instances', to='components.component')),
                ('connected_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_from', to='projects.assemblyitem')),
                ('connection_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_assemblies', to='components.connectionpoint')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.assemblyitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_items', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', '-updated_at'], name='projects_pr_owner_i_242348_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyitem',
            index=models.Index(fields=['project', 'parent'], name='projects_as_project_608075_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyitem',
            index=models.Index(fields=['project', 'connected_to'], name='projects_as_project_64a03f_idx'),
        ),
    ]
