# Generated by Django 5.2.7 on 2025-11-03 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Component Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_file', models.FileField(help_text='Original CAD file (STEP, STL, OBJ, etc.)', upload_to='components/original/')),
                ('glb_file', models.FileField(blank=True, help_text='Converted GLB file for web visualization', null=True, upload_to='components/glb/')),
                ('bounding_box_min_x', models.FloatField(default=0.0)),
                ('bounding_box_min_y', models.FloatField(default=0.0)),
                ('bounding_box_min_z', models.FloatField(default=0.0)),
                ('bounding_box_max_x', models.FloatField(default=0.0)),
                ('bounding_box_max_y', models.FloatField(default=0.0)),
                ('bounding_box_max_z', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0, help_text='Component volume in cubic units')),
                ('center_x', models.FloatField(default=0.0)),
                ('center_y', models.FloatField(default=0.0)),
                ('center_z', models.FloatField(default=0.0)),
                ('is_mountable', models.BooleanField(default=True, help_text='Can this component be mounted to others?')),
                ('mountable_sides', models.JSONField(default=list, help_text='List of mountable side identifiers (e.g., ["top", "bottom", "front"])')),
                ('supported_orientations', models.JSONField(default=list, help_text='Supported rotation constraints')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_components', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='components.componentcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Identifier for this connection point', max_length=100)),
                ('connection_type', models.CharField(choices=[('mount', 'Mount Point'), ('socket', 'Socket'), ('screw', 'Screw Hole'), ('magnetic', 'Magnetic'), ('snap', 'Snap Fit'), ('custom', 'Custom')], default='mount', max_length=20)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('position_z', models.FloatField()),
                ('normal_x', models.FloatField(default=0.0)),
                ('normal_y', models.FloatField(default=0.0)),
                ('normal_z', models.FloatField(default=1.0)),
                ('diameter', models.FloatField(default=0.0, help_text='Connection point diameter/size')),
                ('compatible_types', models.JSONField(default=list, help_text='List of compatible connection types')),
                ('side_label', models.CharField(blank=True, help_text='Side identifier (e.g., "top", "bottom")', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_points', to='components.component')),
            ],
            options={
                'ordering': ['component', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['category', 'processing_status'], name='components__categor_5c7c71_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['name'], name='components__name_dcd38a_idx'),
        ),
        migrations.AddIndex(
            model_name='connectionpoint',
            index=models.Index(fields=['component', 'connection_type'], name='components__compone_23d303_idx'),
        ),
    ]
