# Generated by Django 5.2.7 on 2025-11-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='component',
            name='components__categor_5c7c71_idx',
        ),
        migrations.RemoveField(
            model_name='component',
            name='bounding_box_max_x',
        ),
        migrations.RemoveField(
            model_name='component',
            name='bounding_box_max_y',
        ),
        migrations.RemoveField(
            model_name='component',
            name='bounding_box_max_z',
        ),
        migrations.RemoveField(
            model_name='component',
            name='bounding_box_min_x',
        ),
        migrations.RemoveField(
            model_name='component',
            name='bounding_box_min_y',
        ),
        migrations.RemoveField(
            model_name='component',
            name='bounding_box_min_z',
        ),
        migrations.RemoveField(
            model_name='component',
            name='category',
        ),
        migrations.RemoveField(
            model_name='component',
            name='center_x',
        ),
        migrations.RemoveField(
            model_name='component',
            name='center_y',
        ),
        migrations.RemoveField(
            model_name='component',
            name='center_z',
        ),
        migrations.RemoveField(
            model_name='component',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='component',
            name='description',
        ),
        migrations.RemoveField(
            model_name='component',
            name='is_mountable',
        ),
        migrations.AddField(
            model_name='component',
            name='bounding_box',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='component',
            name='category_label',
            field=models.CharField(choices=[('Motor', 'Motor'), ('Roller', 'Roller'), ('Belt', 'Belt'), ('Frame', 'Frame'), ('Base', 'Base')], default='Base', max_length=32),
        ),
        migrations.AddField(
            model_name='component',
            name='center',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='component',
            name='compatible_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='component',
            name='glb_file',
            field=models.FileField(blank=True, help_text='Converted GLB for web', null=True, upload_to='components/glb/'),
        ),
        migrations.AlterField(
            model_name='component',
            name='mountable_sides',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='component',
            name='original_file',
            field=models.FileField(help_text='CAD file (STEP, STL, OBJ, GLB)', upload_to='components/original/'),
        ),
        migrations.AlterField(
            model_name='component',
            name='supported_orientations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='component',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['category_label', 'processing_status'], name='components__categor_d37e99_idx'),
        ),
    ]
