# Generated by Django 5.2.7 on 2025-11-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_remove_component_components__categor_5c7c71_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='glb_file',
            field=models.FileField(blank=True, help_text='GLB file for web visualization', null=True, upload_to='components/glb/'),
        ),
        migrations.AlterField(
            model_name='component',
            name='original_file',
            field=models.FileField(help_text='GLB/GLTF file (no CAD conversion needed)', upload_to='components/original/'),
        ),
    ]
